//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int KitapId { get; set; }
        public string KitapAdi { get; set; }
        public string Yazari { get; set; }
        public bool KitapStatus { get; set; }
    }
}
